run:
  timeout: 5m
linters:
  enable:
    - dogsled
    - dupl
    - gofmt
    - gofumpt
    - gosec
    - misspell
    - nakedret
    - revive
    - stylecheck
    - unconvert
    - unparam
    - whitespace
    - tagliatelle
    - thelper
    - tparallel
    - unconvert
    - wastedassign
issues:
  exclude-rules:
    - linters:
        - dupl
      path: _test\.go
