project_name: alpen
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: ./
    binary: alpen
    ldflags:
      - -s -w
      - -X github.com/nekrassov01/alpen/main.Version={{.Version}}
      - -X github.com/nekrassov01/alpen/main.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Version }}-devel"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
brews:
  - repository:
      owner: nekrassov01
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    description: "Access log parser/encoder CLI"
    homepage: "https://github.com/nekrassov01/alpen"
    license: "MIT"
    folder: Formula
