name: CI
on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - "README.md"
    tags-ignore:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches:
      - main
      - master
    paths-ignore:
      - "README.md"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
          cache: false

      - name: Unshallow
        run: git fetch --prune --unshallow --tags

      - name: Build
        run: make build

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          args: --timeout=10m
          # https://github.com/golangci/golangci-lint-action/issues/244
          skip-pkg-cache: true
          skip-build-cache: true

      - name: Run govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: 1.21
          go-package: ./...
          cache: false

      - name: Run tests
        run: |
          git diff --cached --exit-code
          make test
          make bench
          make vet
          make cover

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: cover.html
